
--exec msdb.dbo.sp_update_job @job_name = "SBD - JOB RESUME", @enabled = 0

--ALTER DATABASE IPASGO SET PARTNER OFF


--ALTER DATABASE IPASGO SET READ_COMMITTED_SNAPSHOT  ON WITH ROLLBACK IMMEDIATE;

--ALTER DATABASE IPASGO SET ALLOW_SNAPSHOT_ISOLATION ON;


--ALTER DATABASE IPASGO SET PARTNER ON

--exec msdb.dbo.sp_update_job @job_name = "SBD - JOB RESUME", @enabled = 1



ALTER DATABASE [SUSDB] SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE [SUSDB] SET READ_COMMITTED_SNAPSHOT  ON WITH ROLLBACK IMMEDIATE;

ALTER DATABASE [SUSDB] SET ALLOW_SNAPSHOT_ISOLATION ON;

/*No servidor espelho //HAWAII*/
ALTER DATABASE CONTAS_PAGAR 
   SET PARTNER = N'TCP://BDHomologacao:5022'

/*No servidor principal //BDHomologacao*/
ALTER DATABASE CONTAS_PAGAR 
   SET PARTNER = N'TCP://HAWAII:5022'

ALTER DATABASE CONTAS_PAGAR 
   SET WITNESS = N'TCP://BDHomologacao:5022'

ALTER DATABASE Contas_Pagar SET MULTI_USER
