--Criação das URLS de cada Bó servidor

ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'NORTE' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://NORTE.ipasgo.go.gov.br:1433'));

ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'SUL' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://SUL.ipasgo.go.gov.br:1433'));

ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'SUDESTE' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://SUDESTE.ipasgo.go.gov.br:1433'));




--Criação das rotas de cada Nó servidor
ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'NORTE' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('SUL', 'SUDESTE', 'NORTE')));

ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'SUL' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('NORTE', 'SUDESTE', 'SUL')));

 ALTER AVAILABILITY GROUP [gd_Ipasgo]
 MODIFY REPLICA ON N'SUDESTE' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('NORTE', 'SUL', 'SUDESTE')));



select g.name, r1.replica_server_name, l.routing_priority, r2.replica_server_name, r2.read_only_routing_url 
from sys.availability_read_only_routing_lists as l
join sys.availability_replicas as r1 on l.replica_id = r1.replica_id
join sys.availability_replicas as r2 on l.read_only_replica_id = r2.replica_id
join sys.availability_groups as g on r1.group_id = g.group_id
order by g.name, r1.replica_server_name, routing_priority




-- HOMOLOGACAO
ALTER AVAILABILITY GROUP [gd_Homologa]
 MODIFY REPLICA ON N'AUSTRALIA' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://AUSTRALIA.ipasgo.go.gov.br:1433'));

ALTER AVAILABILITY GROUP [gd_Homologa]
 MODIFY REPLICA ON N'INDONESIA' WITH (SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://INDONESIA.ipasgo.go.gov.br:1433'));



 ALTER AVAILABILITY GROUP [gd_Homologa]
 MODIFY REPLICA ON N'AUSTRALIA' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('INDONESIA', 'AUSTRALIA')));

 ALTER AVAILABILITY GROUP [gd_Homologa]
 MODIFY REPLICA ON N'INDONESIA' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('AUSTRALIA', 'INDONESIA')));



ALTER AVAILABILITY GROUP [gd_Homologa2]
MODIFY REPLICA ON N'AUSTRALIA' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('INDONESIA','AUSTRALIA')));

ALTER AVAILABILITY GROUP [gd_Homologa2]
MODIFY REPLICA ON N'INDONESIA' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('AUSTRALIA', 'INDONESIA')));



--Criação das rotas de cada Nó servidor Ambiete de teste
ALTER AVAILABILITY GROUP [gd_ASSISTENCIATEST]
 MODIFY REPLICA ON N'NORTETESTE' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('SULTESTE', 'SUDESTETESTE', 'NORTETESTE')));

ALTER AVAILABILITY GROUP [gd_ASSISTENCIATEST]
 MODIFY REPLICA ON N'SULTESTE' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('NORTETESTE', 'SUDESTETESTE', 'SULTESTE')));

 ALTER AVAILABILITY GROUP [gd_ASSISTENCIATEST]
 MODIFY REPLICA ON N'SUDESTETESTE' WITH  (PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('NORTETESTE', 'SULTESTE', 'SUDESTETESTE')));
